appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: jj0u3IsKh0nvn60c44Z802A6aaeSh7BjQExRCFpJQKcXVQEG0xJsFjPAyd4nlEt/UkeAMoHU7XcswST+B/0sylJ5UyyxkvqA0fiJqAJJ823St4YN0oyJ5RH8JwG3szstzs1Ksb2VbL6FgPDMAnL0b8i/Yrh7arrG5LOg9uVn/x9MjT65blRA332dqN+4mVYIG+UiN7NR5YYAWTfP8DV5eAYn0vN+0WHJT2G6U1GmXJA5jbj2RpeX+gJSNhryZsyPLkNlF9MJxzUJZAPpz5ZZjKIZCK59xMFSPvHbKFBwxkzi7IeQlflayk+Tl+77CfVXELeIctaUagvM4wyEdwNYSkGtId/YAuxZkbTrs+2U3ITDUBQ+CDE1z7DVnoqi/0FN35D/pp5AolcUGXJInJce9BmU39t/zEmAdPM4I5vBEW1dzUh+ycXAb446EiXzNgjV7wj/lf2R5MNvTvKnxUXj9WynDnQz0w686bcJBZfpb0qUlHQa2QXEVu3AUymWeJpfORZM5msFTUvGoi6I1Xv3CRchwzhnwfy7kkTLZMaDApIl473RpudMihXA/ZTb8PBUqu/TNamVQOjNvfFVhVXlNEjOsPgKt3+N36YzCONd9o4dib8a9D8g6zXGVrEyHIK7npXCkIssISmRPblVPpnfWMR0JN3pd4bTKHzGfP3Sut0=
conda_forge_output_validation: true
